# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django_enum.fields
import django_enum.operations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django_enum.operations.CreateEnum(
            db_type='tests_enum_testenum',
            values=['Third value is the best', 'The second value', 'The first value'],
        ),
        django_enum.operations.CreateEnum(
            db_type='test_enum_meta',
            values=['Third value is the best', 'First meta value', 'So meta'],
        ),
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_enum', django_enum.fields.EnumField(type_name='tests_enum_testenum')),
                ('meta_enum', django_enum.fields.EnumField(type_name='test_enum_meta')),
            ],
        ),
    ]
